language: c

dist: xenial

os:
 - linux
 - osx

before_install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm -f /usr/local/include/c++ ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mlkit ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y mlton make ; fi

install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make clean all ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MLCOMP=mlton make clean all ; fi

script:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make test ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MLCOMP=mlton make test ; fi
